export const OPERACIONES = {
  SUMA: 'suma',
  RESTA: 'resta',
  MULTIPLICACION: 'multiplicacion',
  DIVISION: 'division',
  DIVISION_ENTERA: 'division_entera',
  DIVISION_DECIMAL: 'division_decimal',
  DIVISION_RESTO: 'division_resto',
};

OPERACIONES.enteras = [
  OPERACIONES.SUMA,
  OPERACIONES.RESTA,
  OPERACIONES.MULTIPLICACION,
  OPERACIONES.DIVISION_ENTERA];
OPERACIONES.base = [
  OPERACIONES.SUMA,
  OPERACIONES.RESTA,
  OPERACIONES.MULTIPLICACION,
  OPERACIONES.DIVISION];
OPERACIONES.selecionables = [
  OPERACIONES.SUMA,
  OPERACIONES.RESTA,
  OPERACIONES.MULTIPLICACION,
  OPERACIONES.DIVISION,
  OPERACIONES.DIVISION_RESTO,
];
export default OPERACIONES;
