// Generated by Selenium IDE
const $ = require('jquery');
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

const chai = require('chai');
const expect = require('chai').expect;

const Decimal = require('decimal.js');

const OPERACIONES = {
  SUMA: 'suma',
  RESTA: 'resta',
  MULTIPLICACION: 'multiplicacion',
  DIVISION: 'division',
  DIVISION_ENTERA: 'division_entera',
  DIVISION_DECIMAL: 'division_decimal',
  DIVISION_RESTO: 'division_resto',
};

let driver;
let vars;

// responder bien
const solveCurrentOperation = async () => {
  let opActual = {};
  await driver.findElement(By.css('.operacion'))
  .getAttribute('innerHTML')
  .then( (operacionHtml) => {
    vars.html = operacionHtml;
    opActual = driver.executeScript("return opActual;");
    // console.log('vars fin de innerhtml.then', vars);
  });
  await opActual.then( (opAct) => {
    // console.log('opActual', opAct)
    vars.operandos = opAct.operandos;
    switch (opAct.tipo) {
      case OPERACIONES.SUMA:
      vars.resultado = vars.operandos[0] + vars.operandos[1];
      break;
      case OPERACIONES.RESTA:
      vars.resultado = vars.operandos[0] - vars.operandos[1];
      break;
      case OPERACIONES.MULTIPLICACION:
      vars.resultado = new Decimal(vars.operandos[0]).mul(vars.operandos[1]);
      break;
      case OPERACIONES.DIVISION:
      vars.resultado = new Decimal(vars.operandos[0]).div(vars.operandos[1]);    
      break;
    }
  });
  // await console.log('vars.resultado', vars.resultado);
}  
//responde la operacion mal!
const onlyBadAnwsers = async () => {
  let opActual = {};
  await driver.findElement(By.css('.operacion'))
  .getAttribute('innerHTML')
  .then( (operacionHtml) => {
    vars.html = operacionHtml;
    opActual = driver.executeScript("return opActual;");
  });    
  await opActual.then( (opAct) => {                    
    vars.operandos = opAct.operandos;
    switch (opAct.tipo) {
      case OPERACIONES.SUMA:
      vars.resultado = vars.operandos[0] + vars.operandos[1] + 5;    
      break;
      case OPERACIONES.RESTA:
      vars.resultado = vars.operandos[0] - vars.operandos[1] + 5;    
      break;
      case OPERACIONES.RESTA:
      vars.resultado = vars.operandos[0] - vars.operandos[1] + 5;    
      break;
      case OPERACIONES.MULTIPLICACION:
      vars.resultado = new Decimal(vars.operandos[0]).mul(vars.operandos[1])  + 5;    
      break;
    }
  });      
}  

describe('Suma 2 operandos', function() {
  this.timeout( 60 * 1000 );
  
  const suma2Operandos = async () => {
    await driver.get("http://localhost:9012/")
    await driver.executeScript("window.debugSelenium = true;");
    await driver.manage().window().setRect(925, 731)
    await driver.findElement(By.id("btnSuma")).click()
    await driver.executeScript("window.scrollTo(0,1026)")
    await driver.findElement(By.css(".un-char:nth-child(1)")).click()
    await driver.findElement(By.id("btnComenzar")).click()   
    
    for (let i = 0; i < 5; i++) {
      // console.log('operacion', i );
      await solveCurrentOperation();
      await driver.findElement(By.css(".incognita")).sendKeys(vars.resultado);
      // envia resultado
      await driver.findElement(By.css(".incognita")).sendKeys(Key.ENTER)
      // console.log('espera hasta que desaparesca el feedback');
      // await driver.wait( until.elementLocated(By.css('.correcta')) );
      // console.log('localizado, espera que sea visible');
      await driver.wait( until.elementIsVisible(
          driver.findElement(By.css(".incognita"))
      ));
      // console.log('incognita es visible\n\n');
      // pica en continuar
      // await driver.findElement(By.css(".incognita")).sendKeys(Key.ENTER)
    }
    for (let i = 0; i < 5; i++) {
      // console.log('operacion', i+5 );
      await onlyBadAnwsers();
      await driver.findElement(By.css(".incognita")).sendKeys(vars.resultado);
      await driver.findElement(By.css(".incognita")).sendKeys(Key.ENTER)
      const bntReintentar = By.css(".reintentar .button");
      await driver.wait( until.elementIsVisible(
        driver.findElement(By.css(".incognita"))
        ));
        // console.log('incognita es visible\n\n');
        // pica en continuar
        // await driver.findElement(By.css(".incognita")).sendKeys(Key.ENTER)
      }
      for (let i = 0; i < 5; i++) {
        // console.log('operacion', i+5 );
        await onlyBadAnwsers();
        await driver.findElement(By.css(".incognita")).sendKeys(vars.resultado);
        await driver.findElement(By.css(".incognita")).sendKeys(Key.ENTER)
        const bntReintentar = By.css(".reintentar .button");
        await driver.wait( until.elementIsVisible(
          driver.findElement(bntReintentar)
          ));
          await driver.findElement(bntReintentar).click()
          await driver.findElement(By.tagName('body')).sendKeys(Key.ENTER)
          // TODO: NO APARECE EL MENSAJE DE RESPUESTA INCORRECTA EN LA ULTIMA
          // PREGUNTA
          if (i != 4 ){        
            const bntContinuar = By.css(".incorrecta .button");
            await driver.wait( until.elementIsVisible(
              driver.findElement(bntContinuar)
              ));
              await driver.findElement(bntContinuar).click();      
            } 
            // else console.log('fin');
            // console.log('\n');
          }
          
          await driver.wait( until.elementIsVisible(
            driver.findElement(By.id("puntuacion"))
            ));
            await driver.findElement(By.id("puntuacion"))    
            .getAttribute('innerHTML')
            .then( (puntuacion) => {
              vars.puntuacion = puntuacion;
              // console.log('puntuacion', vars.puntuacion);
            });
            await driver.findElement(By.id("aciertos"))    
            .getAttribute('innerHTML')
            .then( (aciertos) => {
              vars.aciertos = aciertos;
              // console.log('aciertos', vars.aciertos);
            });
            await driver.findElement(By.id("fallos"))    
            .getAttribute('innerHTML')
            .then( (fallos) => {
              vars.fallos = fallos;
              // console.log('aciertos', vars.fallos);
            });
          };
          
          // antes de toda la suit
          before( async function() {
            vars = {}
          })
          
          // antes de cada operacion
          beforeEach(async function() {
            driver = await new Builder().forBrowser('firefox').build()
          })
          
          afterEach(async function() {
            await driver.quit();
          })
          
          
          it('Suma 2 operandos Puntuacion ok', async function() {
            if ( !(vars && vars.puntuacion) ) {
              await suma2Operandos();
            }
            // console.log('vars.puntuacion',vars.puntuacion );
            expect(vars.puntuacion).to.equal('5', vars.puntuacion);
          })
          
          it('Suma 2 operandos Aciertos ok', async function() {
            if ( !(vars && vars.puntuacion) ) {
              await suma2Operandos();
            }
            // console.log('vars.aciertos',vars.aciertos );
            expect(vars.aciertos).to.equal('5',vars.aciertos);
          })
          
          it('Suma 2 operandos Fallos ok', async function() {
            if ( !(vars && vars.fallos) ) {
              await suma2Operandos();
            }
            
            // console.log('vars.fallos',vars.fallos );
            expect(vars.fallos).to.equal('5');
            
          })
        })
        