// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Tests Pruebas Firefox', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('test1', async function() {
    await driver.get("http://localhost:9012/")
    await driver.findElement(By.css("#main > .mt-3")).click()
    await driver.findElement(By.id("switch-limiteOp")).click()
    await driver.findElement(By.id("switch-limiteOp")).click()
    await driver.findElement(By.id("switch-limiteOp")).click()
    await driver.findElement(By.css(".tiposNumero > div")).click()
    await driver.findElement(By.id("btnNegativos")).click()
    await driver.findElement(By.id("btnDecimales")).click()
    await driver.findElement(By.id("btnPositivos")).click()
    await driver.findElement(By.css(".un-char:nth-child(1)")).click()
    await driver.findElement(By.css(".un-char:nth-child(2)")).click()
    await driver.findElement(By.css(".un-char:nth-child(1)")).click()
    await driver.findElement(By.id("btnComenzar")).click()
    await driver.findElement(By.id("btnEnviarRespuesta")).click()
  })
})


describe('chrome', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('test1', async function() {
    await driver.get("http://localhost:9012/")
    await driver.findElement(By.css("#main > .mt-3")).click()
    await driver.findElement(By.id("switch-limiteOp")).click()
    await driver.findElement(By.id("switch-limiteOp")).click()
    await driver.findElement(By.id("switch-limiteOp")).click()
    await driver.findElement(By.css(".tiposNumero > div")).click()
    await driver.findElement(By.id("btnNegativos")).click()
    await driver.findElement(By.id("btnDecimales")).click()
    await driver.findElement(By.id("btnPositivos")).click()
    await driver.findElement(By.css(".un-char:nth-child(1)")).click()
    await driver.findElement(By.css(".un-char:nth-child(2)")).click()
    await driver.findElement(By.css(".un-char:nth-child(1)")).click()
    await driver.findElement(By.id("btnComenzar")).click()
    await driver.findElement(By.id("btnEnviarRespuesta")).click()
  })
})
